//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logrotate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logrotate.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding to config files to process.
        /// </summary>
        public static string AddingConfigFile {
            get {
                return ResourceManager.GetString("AddingConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files to rotate.
        /// </summary>
        public static string AddingFileToRotate {
            get {
                return ResourceManager.GetString("AddingFileToRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting alternate state file to.
        /// </summary>
        public static string AlternateStateFile {
            get {
                return ResourceManager.GetString("AlternateStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing rotated log file.
        /// </summary>
        public static string Compressing {
            get {
                return ResourceManager.GetString("Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        public static string Copying {
            get {
                return ResourceManager.GetString("Copying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2012-2013 Ken Salter.
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not be found.
        /// </summary>
        public static string CouldNotBeFound {
            get {
                return ResourceManager.GetString("CouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new empty log file.
        /// </summary>
        public static string CreateNewEmptyLogFile {
            get {
                return ResourceManager.GetString("CreateNewEmptyLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug option set to true.
        /// </summary>
        public static string DebugOptionSet {
            get {
                return ResourceManager.GetString("DebugOptionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting file.
        /// </summary>
        public static string DeletingFile {
            get {
                return ResourceManager.GetString("DeletingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error renaming file.
        /// </summary>
        public static string ErrorRenamingFile {
            get {
                return ResourceManager.GetString("ErrorRenamingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing.
        /// </summary>
        public static string Executing {
            get {
                return ResourceManager.GetString("Executing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing FirstAction commands.
        /// </summary>
        public static string ExecutingFirstAction {
            get {
                return ResourceManager.GetString("ExecutingFirstAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing LastAction commands.
        /// </summary>
        public static string ExecutingLastAction {
            get {
                return ResourceManager.GetString("ExecutingLastAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Postrotate (SharedScripts) commands.
        /// </summary>
        public static string ExecutingPostRotateSharedScripts {
            get {
                return ResourceManager.GetString("ExecutingPostRotateSharedScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Prerotate (SharedScripts) commands.
        /// </summary>
        public static string ExecutingPreRotateSharedScripts {
            get {
                return ResourceManager.GetString("ExecutingPreRotateSharedScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution output.
        /// </summary>
        public static string ExecutionOutput {
            get {
                return ResourceManager.GetString("ExecutionOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to extension is in taboo list.
        /// </summary>
        public static string ExtInTaboo {
            get {
                return ResourceManager.GetString("ExtInTaboo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force option is set, will rotate.
        /// </summary>
        public static string ForceOptionRotate {
            get {
                return ResourceManager.GetString("ForceOptionRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force option set to true.
        /// </summary>
        public static string ForceOptionSet {
            get {
                return ResourceManager.GetString("ForceOptionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global options must go above sections, ignoring.
        /// </summary>
        public static string GlobalOptionsAboveSections {
            get {
                return ResourceManager.GetString("GlobalOptionsAboveSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may be freely redistributed under the terms of the GNU Public License.  .
        /// </summary>
        public static string GNURights {
            get {
                return ResourceManager.GetString("GNURights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file is empty.
        /// </summary>
        public static string LogFileEmpty {
            get {
                return ResourceManager.GetString("LogFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for folders found in.
        /// </summary>
        public static string LookingForFolders {
            get {
                return ResourceManager.GetString("LookingForFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -m/--mail option not supported, ignoring.
        /// </summary>
        public static string MailOptionSet {
            get {
                return ResourceManager.GetString("MailOptionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched folder.
        /// </summary>
        public static string MatchedFolder {
            get {
                return ResourceManager.GetString("MatchedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matching.
        /// </summary>
        public static string Matching {
            get {
                return ResourceManager.GetString("Matching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new section.
        /// </summary>
        public static string NewSection {
            get {
                return ResourceManager.GetString("NewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files found in.
        /// </summary>
        public static string NoFilesFound {
            get {
                return ResourceManager.GetString("NoFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders found in.
        /// </summary>
        public static string NoFoldersFound {
            get {
                return ResourceManager.GetString("NoFoldersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not rotate since log file is not greater than minimum file size.
        /// </summary>
        public static string NoRotateNotGTMinimumFileSize {
            get {
                return ResourceManager.GetString("NoRotateNotGTMinimumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not rotate since log file timestamp did not meet check policy or it was already rotated..
        /// </summary>
        public static string NoRotateNotGTTimeStamp {
            get {
                return ResourceManager.GetString("NoRotateNotGTTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No date found in status file for path.
        /// </summary>
        public static string NoStatusDate {
            get {
                return ResourceManager.GetString("NoStatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timestamp directives are set true, skipping timestamp check.
        /// </summary>
        public static string NoTimestampDirectives {
            get {
                return ResourceManager.GetString("NoTimestampDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing configuration file.
        /// </summary>
        public static string ParseConfigFile {
            get {
                return ResourceManager.GetString("ParseConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process include directive file.
        /// </summary>
        public static string ProcessInclude {
            get {
                return ResourceManager.GetString("ProcessInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procesing directives included in the global settings.
        /// </summary>
        public static string ProcessingGlobalDirective {
            get {
                return ResourceManager.GetString("ProcessingGlobalDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logrotate.
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read line.
        /// </summary>
        public static string ReadLine {
            get {
                return ResourceManager.GetString("ReadLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming.
        /// </summary>
        public static string Renaming {
            get {
                return ResourceManager.GetString("Renaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate file based on file size.
        /// </summary>
        public static string RotateBasedonFileSize {
            get {
                return ResourceManager.GetString("RotateBasedonFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate will be simulated because Debug is true.
        /// </summary>
        public static string RotateSimulated {
            get {
                return ResourceManager.GetString("RotateSimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will rotate since log file is greater than maximum file size.
        /// </summary>
        public static string RotateWhenMaximumFileSize {
            get {
                return ResourceManager.GetString("RotateWhenMaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotating file.
        /// </summary>
        public static string RotatingFile {
            get {
                return ResourceManager.GetString("RotatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to section(s).
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email to.
        /// </summary>
        public static string SendingEmailTo {
            get {
                return ResourceManager.GetString("SendingEmailTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shredding file.
        /// </summary>
        public static string ShreddingFile {
            get {
                return ResourceManager.GetString("ShreddingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping.
        /// </summary>
        public static string Skipping {
            get {
                return ResourceManager.GetString("Skipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status file located in.
        /// </summary>
        public static string StateFileLocation {
            get {
                return ResourceManager.GetString("StateFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timestamp directives are set true, doing timestamp checks.
        /// </summary>
        public static string TimestampDirectives {
            get {
                return ResourceManager.GetString("TimestampDirectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truncating original log file.
        /// </summary>
        public static string TruncateLogFile {
            get {
                return ResourceManager.GetString("TruncateLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command line argument.
        /// </summary>
        public static string UnknownCmdLineArg {
            get {
                return ResourceManager.GetString("UnknownCmdLineArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown directive.
        /// </summary>
        public static string UnknownDirective {
            get {
                return ResourceManager.GetString("UnknownDirective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown size type.
        /// </summary>
        public static string UnknownSizeType {
            get {
                return ResourceManager.GetString("UnknownSizeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating rotation date in status file.
        /// </summary>
        public static string UpdateStatus {
            get {
                return ResourceManager.GetString("UpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: logrotate [-d|--debug] [-f|--force].
        /// </summary>
        public static string Usage1 {
            get {
                return ResourceManager.GetString("Usage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [-s|--state=statefile] [-v|--verbose] [-?|--help] [--usage].
        /// </summary>
        public static string Usage2 {
            get {
                return ResourceManager.GetString("Usage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;configfile&gt;.
        /// </summary>
        public static string Usage3 {
            get {
                return ResourceManager.GetString("Usage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose option set to true.
        /// </summary>
        public static string VerboseOptionSet {
            get {
                return ResourceManager.GetString("VerboseOptionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with wildcard pattern.
        /// </summary>
        public static string WithWildcardPattern {
            get {
                return ResourceManager.GetString("WithWildcardPattern", resourceCulture);
            }
        }
    }
}
